### PR TITLE
fix from tsdz

### PR DESCRIPTION
**Pull request by JamesCordell**
this is untested but at least I got a file.

### CODE REVIEW

**Comment by stancecoke** [comment]
I don't see any sense in this changes?!

**Comment by scoopy007** [comment]
This battery should be deliverable ... because it is available in german watehouse...Von meinem Samsung Galaxy Smartphone gesendet.
-------- Ursprüngliche Nachricht --------Von: stancecoke <notifications@github.com> Datum: 15.09.20  18:10  (GMT+01:00) An: stancecoke/BMSBattery_S_controllers_firmware <BMSBattery_S_controllers_firmware@noreply.github.com> Cc: Subscribed <subscribed@noreply.github.com> Betreff: Re: [stancecoke/BMSBattery_S_controllers_firmware] fix from tsdz
  (#18) 
I don't see any sense in this changes?!

**Comment by scoopy007** [comment]
Sorry. You can ignore my last mail. You were the wrong receiver.Von meinem Samsung Galaxy Smartphone gesendet.
-------- Ursprüngliche Nachricht --------Von: stancecoke <notifications@github.com> Datum: 15.09.20  18:10  (GMT+01:00) An: stancecoke/BMSBattery_S_controllers_firmware <BMSBattery_S_controllers_firmware@noreply.github.com> Cc: Subscribed <subscribed@noreply.github.com> Betreff: Re: [stancecoke/BMSBattery_S_controllers_firmware] fix from tsdz
  (#18) 
I don't see any sense in this changes?!

**Comment by JamesCordell** [comment]
I did not install stm8-binutils-gdb therefor I did not get the bin file. So Iooked at the tsdz project which has a similar build and noticed that is was updated with the following bits in my pull request. Therefore, there must be some sense in these changes.

**Comment by stancecoke** [comment]
All necessary binaries for Windows OS are in the cygwin folder.

**Pull request merged**
