### PR TITLE
A pull request for some changes I made

### PR DESCRIPTION
**Pull request by MartGB**
I fixed and added some stuff, this is not all yet, but I would like to test if this is the right way of pushing the changes

### CODE REVIEW

**Comment by casainho** [comment]
This is up to @stancecoke to accept.

**Comment by stancecoke** [comment]
I can't test Kunteng things any longer, as I have no Kunteng any more. I have to trust, that it works :-)

**Comment by Xnyle** [comment]
I'm still here but not active during winter time. If i find the time i'll review the changes and check if my setup still works with them, also there are some performance related fixes in another branch but that will have to wait at least until spring as well ;-)

**Comment by MartGB** [comment]
> I'm still here but not active during winter time. If i find the time i'll review the changes and check if my setup still works with them, also there are some performance related fixes in another branch but that will have to wait at least until spring as well ;-)

You mean the x4 torque branch right? Or are there other performance improvements for PAS systems too?

**Pull request merged**
